### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/dsn1674-assignment-4#2]
I can't figure out how to have my images resize like the border around it when the browser width changes.

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
Target your images in CSS and give them a width, like:

``` css
img {
  width: 100%;
}
```

**Comment by hldouglas** [comment]
Okay, but now the image doesn't resize inside the border I've made.

**Comment by thomasjbradley** [comment]
Right here in the code:
https://github.com/hldouglas/dsn1674-assignment-4/blob/gh-pages/css/main.css#L80

There is a `max-width`, which probably should be removed—it will disallow the images ever getting bigger than their original size.

**Comment by hldouglas** [comment]
Changed it, still not inside the border.

**Comment by thomasjbradley** [comment]
Instead of using `margin` on the `img` to create space around the border, try `padding` on the `figure`.
