### ISSUE TITLE
Cite problems

### ISSUE THREAD

**Issue by hldouglas** [hldouglas/dsn1674-assignment-4#3]
Cite no longer aligns to the right

**Comment by hldouglas** [comment]
@thomasjbradley

**Comment by thomasjbradley** [comment]
If you highlight the `cite` tag in your developer tools you'll see that it isn't stretching across the whole line, it's only taking up as much space as it needs.

It needs a property added to it that will force it to stretch all they way across its own line.

**Comment by hldouglas** [comment]
Found out what the problem was, it was a typo.
